//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSITEBANSACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string TaikhoanAdmin { get; set; }
        public string MatkhauAdmin { get; set; }
        public string Hoten { get; set; }
    }
}
