//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSITEBANSACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int MaDonHang { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> DaThanhToan { get; set; }
        public int MASACHCT { get; set; }
    
        public virtual CHITIETSACH CHITIETSACH { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
