//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSITEBANSACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public string MaSoQC { get; set; }
        public string Mota { get; set; }
        public string URLLienKet { get; set; }
        public string URLHinh { get; set; }
        public Nullable<decimal> Solanclick { get; set; }
    }
}
