//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSITEBANSACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public SACH()
        {
            this.CHITIETSACHes = new HashSet<CHITIETSACH>();
        }
    
        public int MaSach { get; set; }
        public string Tensach { get; set; }
        public string MaTacGia { get; set; }
    
        public virtual ICollection<CHITIETSACH> CHITIETSACHes { get; set; }
        public virtual TACGIA TACGIA { get; set; }
    }
}
