//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSITEBANSACH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SACHEntities13 : DbContext
    {
        public SACHEntities13()
            : base("name=SACHEntities13")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public DbSet<CHITIETSACH> CHITIETSACHes { get; set; }
        public DbSet<CHUDE> CHUDEs { get; set; }
        public DbSet<DONHANG> DONHANGs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LienKet> LienKets { get; set; }
        public DbSet<NHAXUATBAN> NHAXUATBANs { get; set; }
        public DbSet<QuangCao> QuangCaos { get; set; }
        public DbSet<SACH> SACHes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TACGIA> TACGIAs { get; set; }
        public DbSet<TinTuc> TinTucs { get; set; }
    }
}
