//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBSITEBANSACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACGIA
    {
        public TACGIA()
        {
            this.SACHes = new HashSet<SACH>();
        }
    
        public string MaTacGia { get; set; }
        public string TenTacGia { get; set; }
        public string Diachi { get; set; }
        public string Tieusu { get; set; }
        public string DienThoai { get; set; }
    
        public virtual ICollection<SACH> SACHes { get; set; }
    }
}
